# Tarea 1 Bases de Datos 2022-1 Grupo XX

_Recuerde modificar esta celda y la siguiente! (Borre esta línea también)._

## Integrantes:
* Nombre Integrante 1 - Rol-1
* Nombre Integrante 2 - Rol-2
* Nombre Integrante 3 - Rol-3

## Requisitos para Correr el Notebook

Para poder utilizar este Notebook se debe tener instalado:
- **Python 3**
- **Jupyter**
- La librería **ipython-sql** (Poder ejecutar sql en Jupyter Notebook)
- ToolKit **sqlalchemy**
- PostgreSQL y su conector desde Python(**psycopg2**)

**IMPORTANTE:** Este Jupyter Notebook se conectará a su servicio de Base de Datos PostgreSQL de manera **local**, por lo que **no funcionará correctamente en el entorno Google Collab.**

Para instalar las dependencias, ejecute (recuerde actualizar pip3):

In [ ]:
! pip3 install ipython-sql
! pip3 install sqlalchemy
! pip3 install psycopg2

#Use to generate names
! pip3 install names

## Importar dependencias

In [2]:
from datetime import datetime
import random as r
import names
import string

#Librerías para PostgreSQL
import psycopg2

Para conectarse a la base de datos, completen los datos relevantes en la variable DATABASE_URL.

* Cambie `user` por el usuario que utilizó en Postgres para acceder a la Base de Datos. Por defecto `postgres`.
* Cambie `password` por la contraseña de dicho usuario. **Recuerde borrarla antes de entregar su tarea.**
* Cambie `port` por el puerto en que se ejecuta su servicio de Base de Datos. Por defecto `5432`.
* Cambie `database` por el nombre de la BD (Schema) que creó en Postgres.

Ejemplo: `postgresql://postgres:pass_segura@localhost:5432/tarea-bd`

In [4]:
%reload_ext sql
%env DATABASE_URL=postgresql://postgres:mijasef1@localhost:5432/Tarea1

env: DATABASE_URL=postgresql://postgres:mijasef1@localhost:5432/Tarea1

Para conectarse de forma declarativa a la Base de Datos, utilice el siguiente código:

In [5]:
#Recuerde cambiar los valores de USER, DBNAME y PASSWORD por los mismos de la celda superior.
connection = psycopg2.connect(
   host="localhost",
   user="postgres",
   dbname='Tarea1',
   password="mijasef1"
)

print(connection)
cursor = connection.cursor()

<connection object at 0x000001F93610E350; dsn: 'user=postgres password=xxx dbname=Tarea1 host=localhost', closed: 0>

## Crear tablas

Aquí inserta el código SQL que creara las tablas de la base de datos:

### Tabla "Usuarios"

In [42]:
%%sql
CREATE TABLE Usuarios(
    ID_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR (45) NOT NULL,
    apellido VARCHAR (45),
    correo VARCHAR (45) NOT NULL,
    contraseña VARCHAR (45) NOT NULL,
    fecha_registro TIMESTAMP NOT NULL,
    PRIMARY KEY (ID_usuario)
    
);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

### Tabla "Creadores"

In [43]:
%%sql
CREATE TABLE Creadores (
    ID_creador INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR (45) NOT NULL,
    apellido VARCHAR (45) NOT NULL,
    popularidad INTEGER,
    Estilo VARCHAR (45),
    PRIMARY KEY (ID_creador)
    
);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

### Tabla "Tipos_NTF"

In [44]:
%%sql
CREATE TABLE Tipos_NFT (
    ID_tipo INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR (20) NOT NULL,
    PRIMARY KEY (ID_tipo)


);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

### Tabla "NFT"

In [45]:
%%sql
CREATE TABLE NFT(
    ID_nft INTEGER GENERATED BY DEFAULT AS IDENTITY,
    nombre VARCHAR (45) NOT NULL,
    ID_creador INTEGER,
    ID_tipo INTEGER,
    PRIMARY KEY (ID_nft),
    FOREIGN KEY (ID_creador) REFERENCES Creadores(ID_creador),
    FOREIGN KEY (ID_tipo) REFERENCES Tipos_NFT(ID_tipo)
    


);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

### Tabla "Precio NFT"

In [46]:
%%sql
CREATE TABLE Precio_NFT (
    ID_nft INTEGER GENERATED BY DEFAULT AS IDENTITY,
    fecha TIMESTAMP NOT NULL,
    precio INTEGER NOT NULL,
    PRIMARY KEY (ID_nft, fecha),
    FOREIGN KEY (ID_nft) REFERENCES NFT(ID_nft)
    


);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

### Tabla "Usuario tiene NFT"

In [47]:
%%sql
CREATE TABLE Usuario_tiene_NFT(
    id_usuario INTEGER GENERATED BY DEFAULT AS IDENTITY,
    id_nft INTEGER GENERATED BY DEFAULT AS IDENTITY,
    PRIMARY KEY (id_usuario, id_nft),
    FOREIGN KEY (id_usuario) REFERENCES Usuarios(ID_usuario),
    FOREIGN KEY (id_nft) REFERENCES NFT(ID_nft)


);

 * postgresql://postgres:***@localhost:5432/Tarea1
Done.

[]

## Código Generador de Datos

Ejecute este código para cargar datos a las tablas creadas.

PD: Si el codigo tira error por "violar la unicidad de las PK" es por una coincidencia de numeros random, solamente volver a ejecutar el codigo

In [48]:
#Recuerde haber ejecutado todas las celdas anteriores!

# Generador de timestamp aleatorio.
def generate_timestamp():
    year = r.randint(2015,2022)
    month = r.randint(1,12)
    day = r.randint(1,31)
    
    hour = r.randint(0,23)
    minute = r.randint(0,59)
    second = r.randint(0,59)
    
    if month in [4, 6, 9, 11] and day > 30:
        day = 30
        
    if month == 2 and day > 28:
        day = 28
        
    return datetime(year, month, day, hour, minute, second)

def generate_password():
    return ''.join(r.choice(string.ascii_uppercase + string.digits) for x in range(15))

print("Borrando Datos Antiguos...")

# Limpia la base de datos.
connection.commit() # En caso de algun error
query = "TRUNCATE TABLE usuarios, creadores, tipos_nft, nft, precio_nft, usuario_tiene_nft RESTART IDENTITY"
cursor.execute(query)
connection.commit()


print("Generando Datos...")

nft_names = ['Crypto Raptors', 'The Binary Girl', 'Sphere Art', 'Fight Punks', 'Thunder NFT', 'Artistic Alpha', 'Digital Unicorns', 'Bling Bits', 'Secret Stones', 'Crypto Potato', 'Futuristic Realism', 'Nova Auroras', 'Dreamy Imaginations', 'Reflected Light', 'Spells of Genesis', 'Crypto Felines', 'Dose of Art', 'To The Moon', 'Artful Antlers', 
'Butterfly Dust', 'Depressed Dragons', 'Crypto Diamonds', 'Healthy Hedgehogs', 'Crypto Jackpot', 'Minecraft Sphere', 'Crypto Boom', 'Lucky Lizards', 'Rockin Crypto', 'Crystalline Canyon', 'Koala Kickers', 'Clumsy Crocodiles', 'Mountain of Clouds', 'Blizz Blizzard', 'Cryptokitty Ville', 'Cryptonaut', 'Mike Halloween Yodelers', 'The Teacup Pomeranian', 
'Art Dodger', 'Awesome Concept', 'Aliens Abduction', 'Animated Hard Art', 'Ultimate Iconic Crypto (IUC)', 'Hilarious Horses', '1-Love', '0NOZER0', 'Meteorite NFT', 'Bee Token', 'Elephant Treasure Hunt', 'Crypto Life', '1NiTRO', 'Dust Rift', 'Tokenized Superheroes', 'Techno Abstract Aesthetics', 'Digi Gods', 'Outstanding Octopus', 'Panther NFT', 
'Cypherpunk Samurai', 'Rich Rhinos', 'Crypto Punked', 'Funny Frogs', 'Bit NFT', 'Phonetic Phoenix', 'Flame Stinger', 'Fight For The Title', 'Koalas in Love', 'Touchdown', 'Resilient Rats', 'Bloom of Flowers', 'NFT Lord', 'Fair Coin', 'Art Rumble', 'Light Embrace', 'Crypto Bunny Ranch', 'Crypto Pigeon Race', 'Water Wiggle', 'Wowoo World', 
'Crypto Club', 'Crypto Kitties Of War', 'Visionary Crypto', 'Women Power', 'Rainbows Ends', 'Cards of Polo', 'Crypto Kitties', 'Busy Bats', '0xHile', 'Token Watchdogs', 'Non Fungible Nibbles', 'Pandamonium', '3D Me', 'Midas NFTs', 'Graceful Gorillas', 'United Crypto Token (UCT)', 'Crypto Art Gallery', 'Dark Horse Lady', 'Block View', 'Arty Arts', 
'White Storm', 'Krypto Queen', 'Clever Chimp', 'Qat Tree Unicorn', 'Anna Frozen Entertainers', 'Artificial Rocks', '0NOCH0', 'Flame Blade', 'The Gold Betta', 'Doge Pal', 'Elite Fur Dog Race Club', 'Dust Sifter', 'Moonlit Butterfly', 'Art Lover Box', 'Madame Witch', 'Fantasy Token', 'Bitsy', 'Hive City', 'Couch Potato', 'Burger Bits', 'Crypto Potluck', 
'Cyberboxer', 'Calm Crows', 'Crumbs NFT', 'Mint Chocolates', 'Atollon Coral', 'Dapper Dinos', 'Flame Cats', 'Addictive Animals', 'Alice Wonderland Frozen Carolers', 'Coin Dance', 'Giant Coin', 'Silver Lining Pixy', 'Headed Shark Attack', 'Ultimate League Of Paragon', 'Darker Clouds', 'Blue Mood Chip', 'Brush Point', 'Enthusiastic Elephants', 'Ultra Cool Dogs', 
'Pink Sports Cars']

dominios = ["hola.cl", "google.com","usm.cl","prestigio.usm.cl","crypto.co","basededatos.top"]

tipos_nft = [
    ("Imagen",), ("Musica",),("Juegos",), ("Modelo 3D",), ("Pixel",), ("Membresia",),("Arte",),
]

estilos = [
    ("Anime",),("Manga",),("Arte Retro",),("Arte Moderno",),("Impresionismo",),("Barroco",),("Arte Antiguo",),("Arte 3D",),("Paisaje",)
]

n_usuarios = 200
n_creadores = 20
n_nft = len(nft_names)
n_tipos_nft = len(tipos_nft)
n_usuario_tiene_nft = 80

usuarios = []
for _ in range(1, n_usuarios+1):
    nombre = names.get_first_name()
    apellido = names.get_last_name()
    correo = nombre.lower()+"."+apellido[:4].lower()+"@"+r.choice(dominios)
    usuarios.append((nombre,apellido,correo,generate_password(),generate_timestamp()))

creadores = [(names.get_first_name(), names.get_last_name(), r.randint(0,5), r.choice(estilos)) for _ in range(1,n_creadores+1)]

nft = [(nft_names[n], r.randint(1,n_creadores), r.randint(1,n_tipos_nft)) for n in range(n_nft)]

precio_nft = [(r.randint(1,n_nft), generate_timestamp(), r.randint(500, 100000)) for _ in range(300)]

usuario_tiene_nft = [(r.randint(1,n_usuarios),r.randint(1,n_nft)) for _ in range(81)]


insert = [
    "INSERT INTO usuarios (nombre, apellido, correo, contraseña, fecha_registro) VALUES (%s, %s, %s, %s, %s)",
    "INSERT INTO creadores (nombre, apellido, popularidad, estilo) VALUES (%s, %s, %s, %s)",
    "INSERT INTO tipos_nft (nombre) VALUES (%s)",
    "INSERT INTO nft (nombre, id_creador, id_tipo) VALUES (%s, %s, %s)",
    "INSERT INTO precio_nft (id_nft, fecha, precio) VALUES (%s, %s, %s)",
    "INSERT INTO usuario_tiene_nft (id_usuario, id_nft) VALUES (%s, %s)"
]


for usuario in usuarios:
    cursor.execute(insert[0], usuario)

for creador in creadores:
    cursor.execute(insert[1], creador) 

for tipo in tipos_nft:
    cursor.execute(insert[2], tipo)  

for n in nft:
    cursor.execute(insert[3], n)  
    
for precio in precio_nft:
    cursor.execute(insert[4], precio) 
    
for usr in usuario_tiene_nft:
    cursor.execute(insert[5], usr)
    
connection.commit()

print("Todo Listo!")

Borrando Datos Antiguos...
Generando Datos...
Todo Listo!

## Consultas

Escriba aquí las consultas pedidas. Recuerde agregar una descripción _breve_ de cómo funciona la solución. **Escriba las consultas de forma ordenada.**

**NOTA:** Cuando en una consulta diga "X cosa" significa que ustedes deben de elegir ese X por lo que para cualquier otro X debe de funcionar de igual forma.

### Consulta 1
**ID y Nombre del creador de un estilo X con mayor popularidad.**
###### Si hay más de uno, ponga solamente el primero

Ejemplo:

|Id |  Creador      |
|---|-----------|
| 12 |Levi Ackerman |

**Solución:** _Escriba aquí la descripción de su solución._

In [55]:
%%sql

/* Reemplace estas queries por las que resuelven las consultas pedidas. */


SELECT
    * 
FROM 
    Creadores
WHERE estilo = 'Anime'
ORDER BY popularidad DESC
LIMIT 1;

 * postgresql://postgres:***@localhost:5432/Tarea1
1 rows affected.

[(8, 'Bart', 'Stoddard', 5, 'Anime')]

### Consulta 2
**Cantidad de precios que ha tenido históricamente cada NTF.**

Ejemplo:


| NFT     | Cantidad de precios |
|--------------|----------|
| Minecraft Sphere |    3     |
| The Binary Girl     |    7     |
| ...          |   ...    |

**Solución:** _Escriba aquí la descripción de su solución._

In [91]:
%%sql
SELECT nombre as nft ,COUNT(precio) as Cantidad_de_Precios

FROM 
    Precio_NFT NATURAL JOIN NFT
    
GROUP BY nombre

 * postgresql://postgres:***@localhost:5432/Tarea1
124 rows affected.

[('Spells of Genesis', 2),
 ('Dose of Art', 3),
 ('Art Rumble', 1),
 ('Aliens Abduction', 5),
 ('Meteorite NFT', 1),
 ('Atollon Coral', 4),
 ('Minecraft Sphere', 3),
 ('Bling Bits', 6),
 ('United Crypto Token (UCT)', 1),
 ('Depressed Dragons', 1),
 ('Artistic Alpha', 1),
 ('Light Embrace', 2),
 ('Crypto Kitties Of War', 1),
 ('Pink Sports Cars', 3),
 ('Addictive Animals', 2),
 ('Visionary Crypto', 2),
 ('Animated Hard Art', 3),
 ('Lucky Lizards', 3),
 ('Bloom of Flowers', 4),
 ('Flame Stinger', 3),
 ('Art Lover Box', 3),
 ('Doge Pal', 1),
 ('The Gold Betta', 2),
 ('Darker Clouds', 3),
 ('Digital Unicorns', 1),
 ('Digi Gods', 1),
 ('Token Watchdogs', 6),
 ('Futuristic Realism', 1),
 ('0NOCH0', 2),
 ('Wowoo World', 2),
 ('Crypto Felines', 2),
 ('Hilarious Horses', 2),
 ('Ultra Cool Dogs', 2),
 ('Crypto Pigeon Race', 1),
 ('Mint Chocolates', 4),
 ('Rainbows Ends', 1),
 ('1-Love', 3),
 ('Alice Wonderland Frozen Carolers', 1),
 ('Anna Frozen Entertainers', 3),
 ('Rich Rhinos', 2),
 ('Secret Stones', 2),
 ('Crypto Club', 2),
 ('Elite Fur Dog Race Club', 2),
 ('Crumbs NFT', 3),
 ('Crypto Art Gallery', 4),
 ('Mountain of Clouds', 1),
 ('Couch Potato', 3),
 ('Panther NFT', 4),
 ('Hive City', 2),
 ('Cryptokitty Ville', 1),
 ('Moonlit Butterfly', 4),
 ('Crystalline Canyon', 5),
 ('Bee Token', 2),
 ('Brush Point', 4),
 ('Reflected Light', 1),
 ('Outstanding Octopus', 1),
 ('Healthy Hedgehogs', 1),
 ('Crypto Potluck', 4),
 ('Techno Abstract Aesthetics', 2),
 ('Thunder NFT', 4),
 ('Dust Rift', 1),
 ('Giant Coin', 2),
 ('Women Power', 2),
 ('Touchdown', 3),
 ('Funny Frogs', 3),
 ('Midas NFTs', 3),
 ('Calm Crows', 1),
 ('Dark Horse Lady', 1),
 ('Crypto Punked', 3),
 ('Dreamy Imaginations', 1),
 ('Crypto Diamonds', 1),
 ('Madame Witch', 2),
 ('Busy Bats', 1),
 ('Crypto Raptors', 2),
 ('Pandamonium', 4),
 ('Dust Sifter', 3),
 ('Crypto Boom', 3),
 ('Crypto Life', 2),
 ('Krypto Queen', 3),
 ('Koala Kickers', 4),
 ('1NiTRO', 2),
 ('Graceful Gorillas', 4),
 ('To The Moon', 2),
 ('NFT Lord', 1),
 ('Qat Tree Unicorn', 2),
 ('Fight Punks', 1),
 ('Mike Halloween Yodelers', 1),
 ('Koalas in Love', 1),
 ('Fair Coin', 1),
 ('Cyberboxer', 2),
 ('Art Dodger', 5),
 ('Cryptonaut', 4),
 ('0NOZER0', 3),
 ('Sphere Art', 1),
 ('White Storm', 3),
 ('Burger Bits', 2),
 ('The Binary Girl', 3),
 ('The Teacup Pomeranian', 3),
 ('Flame Blade', 2),
 ('Non Fungible Nibbles', 4),
 ('Ultimate League Of Paragon', 1),
 ('Cypherpunk Samurai', 3),
 ('Awesome Concept', 3),
 ('Crypto Potato', 3),
 ('Crypto Bunny Ranch', 3),
 ('3D Me', 1),
 ('Fight For The Title', 3),
 ('Rockin Crypto', 2),
 ('Phonetic Phoenix', 3),
 ('Flame Cats', 2),
 ('Butterfly Dust', 2),
 ('Crypto Kitties', 2),
 ('Silver Lining Pixy', 3),
 ('Enthusiastic Elephants', 1),
 ('Arty Arts', 4),
 ('Clever Chimp', 5),
 ('Blue Mood Chip', 2),
 ('Coin Dance', 2),
 ('Artful Antlers', 1),
 ('Elephant Treasure Hunt', 1),
 ('Block View', 5),
 ('0xHile', 5),
 ('Ultimate Iconic Crypto (IUC)', 3),
 ('Bitsy', 2)]

### Consulta 3
**El nombre y tipo (nombre del tipo) del NFT históricamente más caro.**
###### Si hay más de uno, ponga solamente el primero
Ejemplo:

| NFT    | Tipo | 
|----------------|--------|
| Minecraft Sphere| Arte 3D |

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT nombre, apellido
    * 
FROM 
    Usuarios NATURAL JOIN 
WHERE
    nombre = 'WillyRex';

### Consulta 4
**Nombre y apellido del usuario con más número de NFTs.**

Ejemplo:

| Nombre     | Apellido |
|----------------|--------|
| Levi | Ackerman |

**Solución:** _Escriba aquí la descripción de su solución._

In [88]:
%%sql
SELECT nombre, apellido
     
FROM 
    Usuarios NATURAL JOIN Usuario_tiene_nft
    
GROUP BY nombre, apellido
ORDER BY count(id_usuario) DESC
LIMIT 1

 * postgresql://postgres:***@localhost:5432/Tarea1
1 rows affected.

[('Anne', 'Davis')]

### Consulta 5
**El NFT que más veces cambió de precio historicamente.**

Ejemplo:

|  ID  | NFT | 
|--------|-------|
| 11 |Minecraft Sphere | 

**Solución:** _Escriba aquí la descripción de su solución._

In [101]:
%%sql
SELECT id_nft as id, nombre as nft

FROM 
    Precio_NFT NATURAL JOIN NFT

GROUP BY id_nft, nombre
ORDER BY count(precio) DESC
LIMIT 1

 * postgresql://postgres:***@localhost:5432/Tarea1
1 rows affected.

[(86, 'Token Watchdogs')]

### Consulta 6
**Usuarios que NO tienen un NFT.**

Ejemplo

|Nombre | Apellido|
|--------|-------|
|Guillermo    | Diaz |
|Markus | Person |
|Rick   | Astley |
|... | ...| 

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';

### Consulta 7
**Top 4 NFTs más caros actualmente de un id_tipo X .**

Ejemplo:

|NFT | 
|--------|
|Minecraft Sphere | 
|The Binary Girl |
|Koalas in Love | 
|Art Dodger | 

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';

### Consulta 8
**Los precios de todos los NFTs entre los años 2017 y 2019 inclusive.**

Ejemplo:

|NFT |Precio |
|----|---|
|Minecraft Sphere |  4000 |
|The Binary Girl | 3000| 
| Koalas in Love | 6000 |
|Minecraft Sphere |  1250 |
| ... | ... |

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';

### Consulta 9 
**Creador al cual le han comprado más NFTs.**

Ejemplo:
   
|Nombre |Apellido |Cantidad |
|-|--|-----|
| Levi |Ackerman |32|

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';

### Consulta 10  
**El NFT con mayor precio actual, que pertenezca a un creador X.**

Ejemplo:
   
|NFT |Valor|
|-|-------|
|Minecraft Sphere |18000|

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';

### Consulta BONUS
###### (Vale por un abrazo psicológico)

**El usuario que posee más dinero en NFTs considerando los precios actuales de estos**

Ejemplo:
   
|Usuario |Dinero|
|-|-------|
|Levi Ackerman |8000001|

**Solución:** _Escriba aquí la descripción de su solución._

In [ ]:
%%sql
SELECT
    * 
FROM 
    Creadores
WHERE
    nombre = 'WillyRex';